### ISSUE TITLE
Explore Simple Climate Models and GHG

### ISSUE THREAD

**Issue by derevirn** [e3modelling/OPEN-PROM#232]
# Simple Climate Models
### (Very Brief) Introduction to Climate Modelling
Climate scientists utilize complex models that simulate the global climate system, i.e. mainly the interactions between the atmosphere, oceans, land surface and cryosphere (glaciers, ice sheets etc). Those models are highly complex and require significant resources to be executed, with the purpose of generating a highly detailed simulation that can be utilized in scientific research. Therefore, typical climate models require supercomputers with thousands of CPU cores, making them inaccessible to most users. It should also be noted, that some models follow a more holistic approach, by incorporating the lithosphere, biosphere and even magnetosphere, thus resulting in a complete earth system model.

<img src="https://github.com/e3modelling/OPEN-PROM/assets/9198526/1931d14f-1e88-49e7-88f5-2ce4c6115fa0" width="400">

### Simple Climate Models
Energy system models can calculate greenhouse gas (GHG) emissions that are generated by human activities, such as electricity generation, transport and industrial manufacturing, for various future scenarios. Those emission values can then be utilized by a climate model to calculate atmospheric concentrations of GHG, as well as the global mean temperature increase. Still, coupling a complex climate model with an energy system model would be significantly challenging, due to the necessary resources that were mentioned earlier. Therefore, researchers have created simple climate models (SCM) of reduced complexity and size, to complement energy system models. SCMs do not provide the detail and resolution that is necessary for climate science research, but can generate meaningful results to help explore various climate change mitigation pathways, and inform policy makers. Integrated assessment models (IAM) are typically comprised of an energy system model, a simple climate model, as well as other components depending on each case.

## Tasks
- [ ] Check the [`openscm/pymagicc`](https://github.com/openscm/pymagicc) library that lets us easily use the MAGICC climate model.
- [ ] Check the [`openscm/openscm`](https://github.com/openscm/openscm) tool that provides access to various SCM.
- [ ] Check the [`iiasa/rime`](https://github.com/iiasa/rime) tool for climate impact data. 
- [ ] Check the Cicero Simple Climate Model - [CICERO-SCM](https://github.com/ciceroOslo/ciceroscm)
- [ ] List all important greenhouse gases, as well as their sources, for the purposes of climate modelling.
